### ISSUE TITLE
Unit and e2e test scaffolding for custom blocks

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/ideas#103]
We make it easy for WordPress plugin authors to add (unit) tests with `wp scaffold plugin-tests`.

It would be helpful to have a similar "standard automated testing" pattern for WordPress block authors.

This could even be used to help prevent scenarios like https://github.com/WordPress/gutenberg/issues/3693#issuecomment-347675561

> The blocks in the gutenberg-examples repo don't work, and neither does the code in the "create blocks" tutorial. The code examples are all out of date and need to be updated to keep up with Gutenberg development.

Related https://github.com/WordPress/gutenberg/issues/641
Originally https://github.com/WordPress/gutenberg/issues/3706

**Comment by danielbachhuber** [comment]
@nerrad Do you have anything abstracted at this point that you might be able to share?

**Comment by nerrad** [comment]
What I have right now is still somewhat dependent on the gutenberg package as a whole (because current package releases are still a bit buggy (see https://github.com/WordPress/gutenberg/issues/3955#issuecomment-393482861).  However, once I convert our tests over to using the modular published packages I'll be happy to document/share what we're using.  Maybe a first step will be to get some documentation, writing that out will help (me at least) work out where wp-cli can aid that with a scaffold command.

**Comment by nerrad** [comment]
It should be added though, that coming up with a baseline scaffold for custom block tests _could_ be a hard to iron out because test needs can differ widely among custom block implementations.  For instance some block authors may just need to test using mocks whereas other block authors may want to test using actual gb packages.  However, I suppose a good default would be to have the configuration set to use actual imports and mocks can be implemented at the test level (by block authors if they want)?

Also what were you thinking this scaffold command would do/build?

**Comment by danielbachhuber** [comment]
> Also what were you thinking this scaffold command would do/build?

Basic unit and e2e tests, using the same pattern established by Gutenberg. It could be a prototypical implementation that would need to be modified before use.

**Comment by swissspidy** [comment]
This should be covered by `@wordpress/create-block` nowadays
