### ISSUE TITLE
install Wordpress as a git submodule

### ISSUE THREAD

**Issue by str** [wp-cli/ideas#109]
I've seen many documentation posts about installing Wordpress in a subfoder as a git submodule. I like it because it allows me not to have the core WP files in my git repo and to be able to update WP via git.

It would  be a nice to have if I could do that in a wp-cli command.

**Comment by danielbachhuber** [comment]
Hi @str,

Thanks for the suggestion! A WP-CLI command isn't necessary because you can do this directly with `git` commands. Here's a tutorial I found via a Google Search: https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

With this being said, you may also consider installing WordPress with Composer, which is generally preferable to Git submodules.
