### ISSUE TITLE
Add post term  <termdescription>

### ISSUE THREAD

**Issue by benemohamed** [wp-cli/ideas#129]
## Feature Request

`wp (term) *` https://github.com/wp-cli/entity-command

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**
I can't add new category with Description.
example post category with full options :
`Name` ✔
`Slug` ✔
`Parent Category` ✔
`Description` ❌

```bash
$ wp post term add  1 category test
Success: Added term.
```

**Describe the solution you'd like**

add new parameter `<termdescription>`.

 `<termdescription>` =  `string html`
```bash
$ wp post term add
usage: wp post term add <id> <taxonomy> <term> <termdescription> ... [--by=<field>]
$ # example
$ wp post term add 1 category test '<h1>term description</h1><br>'
Success: Added term.
```

**Comment by schlessera** [comment]
You can already do this, but the description is added through `wp term create` or `wp term update`. This is because `wp post term add` actually only adds the relationship between the post and the term. But if you try to attach a new term, it creates it first, with default settings.

So, for full control, you would create the term yourself (with the description you want), and then attach it to the post (or several of them).

You can do this in one go with the following construct:
```bash
wp post term add 1 category $(wp term create category test --description='<h1>term description</h1><br>' --porcelain)
```

The `--porcelain` flag means it will only return the ID of the freshly created term, which makes it easy to feed into `wp post term add`.

**Comment by schlessera** [comment]
As this problem is already solved with existing functionality, I'll close this issue.
