### ISSUE TITLE
Combine all update commands into one `wp update` command

### ISSUE THREAD

**Issue by Horttcore** [wp-cli/ideas#16]
Combine these commands into one command

`wp core update`
`wp plugin update --all`
`wp theme update --all`
`wp core language update`

`wp update`

**Comment by danielbachhuber** [comment]
Interesting. I've long wanted #19

Also related #10

**Comment by Benosika** [comment]
I would love to have that !

**Comment by joeldcanfield** [comment]
What would be the value in adding this to wp-cli? This is trivial to alias in most shells. I just popped out and created this for my local WP install:

`alias wpupdate='pwd; wp core update; wp plugin update --all; wp theme update --all'`

Added that line to my .zshrc file, and boom. Creating commands that aggregate other commands will get confusing real quick.

Please feel free to point out what I'm missing, because often, I'm missing something!

**Comment by swissspidy** [comment]
Related situation in the language command, where we deliberately split the `update` commands. So this would be a step backward, which I don't see value in. An alias works just as well.
