### ISSUE TITLE
Edit constants and variables defined in wp-config.php

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/ideas#4]
Editing a wp-config.php file programmatically is imprecise and error-prone, when it ideally would be as easy as running a WP-CLI command.

Borek Bernard has some suggestions for how to implement: https://github.com/wp-cli/wp-cli/issues/2501

**Comment by emirpprime** [comment]
Started work on a command to do this. Very much a work in progress but initial functionality works well enough for some testing and input if anyones interested: https://github.com/emirpprime/config-update-command
There are various known problems [BUG] and missing features [TODO] commented in the code.

My starting point was to mimic config variables for familiarity / user expectations rather than introduce new behaviours.

**Comment by danielbachhuber** [comment]
> Started work on a command to do this.

Neat!

For programmatically editing a `wp-config.php` file, I was thinking about creating a new library to serve as an interface for editing the file. This would let us eventually write hundreds of tests for every possible combination of `wp-config.php` (and others could use it in other systems). Something you'd want to help hack on in a few weeks?

**Comment by emirpprime** [comment]
Yes happy to chip in - sounds like it might be a bit above my ability to do the heavy lifting but I'll do what I can!

**Comment by danielbachhuber** [comment]
This was implemented with https://github.com/wp-cli/config-command/pull/44
