### ISSUE TITLE
Shuffle salts in wp-config.php

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/ideas#50]
After https://github.com/wp-cli/ideas/issues/4 is implemented, it'd be neat to have something like `wp config shuffle-salts` that would programmatically generate and write new salt values.

Inspired by https://github.com/wp-cli/config-command/pull/25

**Comment by schlessera** [comment]
This can use the API endpoint provided here: https://api.wordpress.org/secret-key/1.1/salt/

**Comment by danielbachhuber** [comment]
Now that we have https://github.com/wp-cli/wp-config-transformer, this is easily doable.

**Comment by CodeProKid** [comment]
Curious if anyone thinks there are any arguments needed for this command? The only one I can think of would _maybe_ be an argument to optionally create the salts locally rather than from the remote WP server?

Also for messaging, it seems like a simple success/failure message here would suffice. I don't think it needs to be any more verbose than that since there are other commands to read the value of the salts.

**Comment by CodeProKid** [comment]
Looking at core handles this, and it looks like the keys are actually generated on the local machine by default, and only hits the API if that throws an exception. I'm thinking this command should probably mirror that functionality -> https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/setup-config.php#L317-L346

Unfortunately that code isn't abstracted at all, so it will probably lead to some redundant code.

**Comment by schlessera** [comment]
I think the remote calls are only for servers where the necessary encryption extensions/libraries are not present or buggy.

We should always opt to closely mirror Core behavior with WP-CLI, so ideally, we'd just reuse the Core code if possible.

**Comment by danielbachhuber** [comment]
This was implemented in https://github.com/wp-cli/config-command/pull/62
