### ISSUE TITLE
wp db delete

### ISSUE THREAD

**Issue by marksabbath** [wp-cli/ideas#78]
As stated on https://github.com/wp-cli/db-command/issues/51#issuecomment-355920932 there are users that would like to clean up their databases by using `wp db search`, however, the output of `wp db search` is not the ideal to combine commands in shell, so my proposal would be creating a new command, `wp db delete`, where it could accept mostly the same parameters as `wp db search` for searching and delete the records found. Modes like --dry-run or --interactive will be also provided as a safety features.

**Comment by danielbachhuber** [comment]
What's a real-world example of data you might want to delete?

**Comment by danhgilmore** [comment]
@danielbachhuber - We have a SUPER old WPMu installation here at work, and at one time, it offered the K2 theme for use. That theme added a bunch of metadata to the wp_X_options table. Years later, those rows are still in the DB.

**Comment by austinginder** [comment]
Just thought I'd add the following as more or less an alternative using some fancy SQL.

Yes using `wp db search` will find more matches as shown here.
```
wp db search wp-piwik --one_line
wp_options:option_name:529:wp-piwik_global-settings
wp_options:option_name:530:wp-piwik_settings
wp_options:option_value:96:lete_themes";b:1;s:6:"export";b:1;s:19:"wp-piwik_read_stats";b:1;s:10:"gfp_stripe";b:1;s
```

However for the situations where you just need to clean up some records from the wp_options table, you can manually scan the `option_name` column using `wp db query`. With some SQL magic you get this to return just the IDs in csv format.

```
wp db query "SELECT GROUP_CONCAT(option_id SEPARATOR ',') from wp_options where option_name like '%wp-piwik%';" --silent --skip-column-names
529,530
```
Combining this inside another `wp db query` you now have a one liner which will delete records matching a basic search.
```
wp db query "DELETE from wp_options where option_id in ($(wp db query "SELECT GROUP_CONCAT(option_id SEPARATOR ',') from wp_options where option_name like '%wp-piwik%';" --silent --skip-column-names))"
```
Since this is pretty dangerous it's a good idea to take a peak before you delete anything like so.
```
wp db query 'SELECT * FROM wp_options WHERE option_name like "%wp-piwik%"' --skip-column-names 
```

**Comment by schlessera** [comment]
@austinginder Would you mind adding your one-liner solution as an example in the command doc-block of `wp db search`, as a resolution to https://github.com/wp-cli/db-command/issues/51 ?

**Comment by austinginder** [comment]
@schlessera Will do.

**Comment by marksabbath** [comment]
It seems that this has been addressed on https://github.com/wp-cli/db-command/pull/122 and we should be good to close.
